[package]
name = "taki"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
colored = "2.1.0"
crossterm = "0.28.1"
once_cell = "1.20.2"
rand = "0.8.5"
ratatui = "0.29.0"
regex = "1.11.1"
